# Generated by Django 5.0.6 on 2024-06-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_empleado_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=200)),
                ('descripcion_servicio', models.TextField(max_length=550)),
                ('costo_servicio', models.CharField(max_length=100)),
                ('pagina_servicio', models.CharField(max_length=500)),
                ('imagen_servicio', models.ImageField(blank=True, null=True, upload_to='uploads/servicio/')),
            ],
        ),
    ]
