# Generated by Django 5.0.6 on 2024-06-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='costo_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='pagina_servicio',
        ),
    ]
