# Generated by Django 5.0.6 on 2024-06-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_servicio_costo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='multiplicador',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
