# Generated by Django 5.0.6 on 2024-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_precio_final_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrito_viejo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
