# Generated by Django 5.0.6 on 2024-06-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_producto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
