# Generated by Django 5.0.6 on 2024-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
