# Generated by Django 5.0.6 on 2024-06-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_empleado_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
